package com.javacompiler.interpreter;

public enum TokenType {

    INTEGER_LITERAL, DOUBLE_LITERAL, STRING_LITERAL, CHAR_LITERAL,
    BOOLEAN_LITERAL, NULL_LITERAL,

    IDENTIFIER,

    INT, DOUBLE_TYPE, STRING_TYPE, BOOLEAN_TYPE, CHAR_TYPE,
    FLOAT_TYPE, LONG_TYPE,

    PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL,
    VOID, CLASS, NEW, RETURN,
    IF, ELSE, WHILE, FOR, DO, BREAK, CONTINUE,

    PLUS, MINUS, STAR, SLASH, PERCENT,

    ASSIGN,
    PLUS_ASSIGN, MINUS_ASSIGN, STAR_ASSIGN, SLASH_ASSIGN, PERCENT_ASSIGN,

    EQUAL_EQUAL, NOT_EQUAL,
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,

    AND_AND, OR_OR, BANG,


    PLUS_PLUS, MINUS_MINUS,

    LPAREN, RPAREN,
    LBRACE, RBRACE,
    LBRACKET, RBRACKET,
    SEMICOLON, COMMA, DOT,

    EOF
}